# backend/app/schemas/__init__.py
from app.schemas.health import HealthResponse
from app.schemas.crop import CropAnalysisResponse
from app.schemas.soil import (
    SoilAnalysisRequest,
    SoilAnalysisResponse,
    SoilParameters,
    SoilParameterResult,
    CropContext,
)
from app.schemas.weather import (
    WeatherLocation,
    CurrentWeather,
    TodayWeather,
    ForecastDay,
    AgriculturalAlert,
    FarmOutlook,
    WeatherResponse,
    LocationSearchResult,
)
from app.schemas.mandi import (
    MandiQuery,
    MandiPriceRecord,
    MandiSource,
    MandiSummary,
    MandiPriceResponse,
    MandiFilterOptions,
)
from app.schemas.scheme import (
    SchemeSummary,
    SchemeDetail,
    SchemeResponse,
    SchemeFilterMeta,
)
from app.schemas.crop_guide import (
    CropSoilInfo,
    CropSowingInfo,
    CropWaterInfo,
    CropNutritionInfo,
    CropPestDisease,
    CropHarvestInfo,
    CropSummary,
    CropGuideResponse,
    CropListResponse,
)
from app.schemas.assistant import (
    LocationContext,
    CropContextInfo,
    SoilContextInfo,
    CropHealthContextInfo,
    WeatherContextInfo,
    MarketContextInfo,
    FarmerContext,
    AssistantChatRequest,
    SourceMetadata,
    AssistantResponse,
)

__all__ = [
    "HealthResponse",
    "CropAnalysisResponse",
    "SoilAnalysisRequest",
    "SoilAnalysisResponse",
    "SoilParameters",
    "SoilParameterResult",
    "CropContext",
    "WeatherLocation",
    "CurrentWeather",
    "TodayWeather",
    "ForecastDay",
    "AgriculturalAlert",
    "FarmOutlook",
    "WeatherResponse",
    "LocationSearchResult",
    "MandiQuery",
    "MandiPriceRecord",
    "MandiSource",
    "MandiSummary",
    "MandiPriceResponse",
    "MandiFilterOptions",
    "SchemeSummary",
    "SchemeDetail",
    "SchemeResponse",
    "SchemeFilterMeta",
    "CropSoilInfo",
    "CropSowingInfo",
    "CropWaterInfo",
    "CropNutritionInfo",
    "CropPestDisease",
    "CropHarvestInfo",
    "CropSummary",
    "CropGuideResponse",
    "CropListResponse",
    "LocationContext",
    "CropContextInfo",
    "SoilContextInfo",
    "CropHealthContextInfo",
    "WeatherContextInfo",
    "MarketContextInfo",
    "FarmerContext",
    "AssistantChatRequest",
    "SourceMetadata",
    "AssistantResponse",
]

