from typing import List, Optional
from pydantic import BaseModel, Field

class CropAnalysisResponse(BaseModel):
    is_identified: bool = Field(
        default=True,
        description="Whether a recognizable crop/plant and condition could be identified."
    )
    crop: Optional[str] = Field(
        default=None,
        description="Name of the crop or plant (e.g., Tomato, Soybean, Rice, Wheat)."
    )
    possible_condition: Optional[str] = Field(
        default=None,
        description="Assisted diagnosis of possible disease, pest, or healthy state."
    )
    confidence: Optional[float] = Field(
        default=None,
        description="Model confidence estimate between 0.0 and 1.0, if determinable."
    )
    confidence_text: Optional[str] = Field(
        default=None,
        description="Farmer-friendly confidence display string (e.g., '91% (High)')."
    )
    severity: Optional[str] = Field(
        default="Moderate",
        description="Severity level: Healthy, Mild, Moderate, Severe, or Unknown."
    )
    observations: List[str] = Field(
        default_factory=list,
        description="Visible observations and symptoms detected by AI from the image."
    )
    explanation: str = Field(
        default="",
        description="Plain-language explanation of the observed symptoms and disease pattern."
    )
    recommended_actions: List[str] = Field(
        default_factory=list,
        description="Safe, general, non-prescriptive actionable steps the farmer can consider."
    )
    preventive_guidance: List[str] = Field(
        default_factory=list,
        description="Long-term preventive farm hygiene and crop management practices."
    )
    additional_information_needed: List[str] = Field(
        default_factory=list,
        description="Contextual variables needed for deeper diagnosis (e.g., crop age, rainfall)."
    )
    disclaimer: str = Field(
        default="AI-assisted assessment: This result is not a definitive agricultural diagnosis. Confirm important treatment decisions with a qualified agricultural professional or trusted agricultural authority.",
        description="Standard safety and medical decision support notice."
    )
    is_demo: bool = Field(
        default=False,
        description="True if generated by development mock fallback due to missing API configuration."
    )
    error: Optional[str] = Field(
        default=None,
        description="Error message if diagnosis could not proceed."
    )
