"""
Mandi Price Intelligence Constants, State-District Mappings, and Standardized Commodity Configurations.
"""

from typing import Dict, List

# Official Source Attribution
MANDI_SOURCE_INFO = {
    "name": "Government of India Open Government Data (data.gov.in) / Directorate of Marketing & Inspection (AGMARKNET)",
    "url": "https://data.gov.in/resource/current-daily-price-various-commodities-various-markets-mandi",
    "description": "Daily wholesale arrival and modal price records reported by APMC mandis across India under the Ministry of Agriculture & Farmers Welfare.",
}

# Major Supported Agricultural Commodities
SUPPORTED_COMMODITIES = [
    "Soybean",
    "Wheat",
    "Rice",
    "Cotton",
    "Maize",
    "Onion",
    "Tomato",
    "Sugarcane",
    "Gram (Chana)",
    "Mustard",
    "Potato",
    "Tur (Arhar)",
    "Bajra",
    "Jowar",
    "Groundnut",
]

# Commodity Name Normalization Aliases (Case-insensitive matching)
COMMODITY_ALIASES: Dict[str, str] = {
    "soyabean": "Soybean",
    "soybean": "Soybean",
    "soya": "Soybean",
    "wheat": "Wheat",
    "gehun": "Wheat",
    "rice": "Rice",
    "paddy": "Rice",
    "paddy(dhan)": "Rice",
    "dhan": "Rice",
    "cotton": "Cotton",
    "kapas": "Cotton",
    "maize": "Maize",
    "makka": "Maize",
    "corn": "Maize",
    "onion": "Onion",
    "pyaz": "Onion",
    "kanda": "Onion",
    "tomato": "Tomato",
    "tamatar": "Tomato",
    "sugarcane": "Sugarcane",
    "ganna": "Sugarcane",
    "gram": "Gram (Chana)",
    "chana": "Gram (Chana)",
    "bengal gram": "Gram (Chana)",
    "mustard": "Mustard",
    "sarson": "Mustard",
    "potato": "Potato",
    "aloo": "Potato",
    "tur": "Tur (Arhar)",
    "arhar": "Tur (Arhar)",
    "red gram": "Tur (Arhar)",
    "bajra": "Bajra",
    "pearl millet": "Bajra",
    "jowar": "Jowar",
    "sorghum": "Jowar",
    "groundnut": "Groundnut",
    "peanut": "Groundnut",
    "moong": "Moong (Green Gram)",
    "urad": "Urad (Black Gram)",
}

# Standard States & Districts for Agricultural Marketing Filter Options
INDIAN_AGRICULTURAL_STATES: List[str] = [
    "Maharashtra",
    "Madhya Pradesh",
    "Punjab",
    "Haryana",
    "Karnataka",
    "Telangana",
    "Andhra Pradesh",
    "Gujarat",
    "Rajasthan",
    "Uttar Pradesh",
    "Bihar",
    "Tamil Nadu",
]

DISTRICTS_BY_STATE: Dict[str, List[str]] = {
    "Maharashtra": [
        "Pune",
        "Nashik",
        "Nagpur",
        "Kolhapur",
        "Solapur",
        "Ahmednagar",
        "Amravati",
        "Chhatrapati Sambhajinagar",
        "Jalgaon",
        "Latur",
        "Satara",
        "Sangli",
    ],
    "Madhya Pradesh": [
        "Indore",
        "Ujjain",
        "Bhopal",
        "Dewas",
        "Dhar",
        "Sehore",
        "Hoshangabad",
        "Jabalpur",
    ],
    "Punjab": [
        "Ludhiana",
        "Amritsar",
        "Patiala",
        "Jalandhar",
        "Bathinda",
        "Ferozepur",
    ],
    "Haryana": [
        "Karnal",
        "Ambala",
        "Kurukshetra",
        "Hisar",
        "Sirsa",
        "Rohtak",
    ],
    "Karnataka": [
        "Bengaluru",
        "Belagavi",
        "Dharwad",
        "Ballari",
        "Mysuru",
        "Shivamogga",
    ],
    "Telangana": [
        "Hyderabad",
        "Warangal",
        "Nizamabad",
        "Khammam",
        "Karimnagar",
    ],
    "Gujarat": [
        "Ahmedabad",
        "Rajkot",
        "Surat",
        "Vadodara",
        "Junagadh",
        "Amreli",
    ],
    "Rajasthan": [
        "Jaipur",
        "Kota",
        "Jodhpur",
        "Bikaner",
        "Sri Ganganagar",
        "Alwar",
    ],
    "Uttar Pradesh": [
        "Agra",
        "Aligarh",
        "Kanpur",
        "Varanasi",
        "Meerut",
        "Lucknow",
        "Bareilly",
    ],
}

SAMPLE_MARKETS_BY_DISTRICT: Dict[str, List[str]] = {
    "Pune": ["Pune", "Baramati", "Khed", "Manchar", "Junnar", "Shirur", "Indapur"],
    "Nashik": ["Nashik", "Lasalgaon", "Pimpalgaon", "Malegaon", "Yeola", "Sinnar"],
    "Nagpur": ["Nagpur", "Katol", "Kalmeshwar", "Saoner", "Umred"],
    "Kolhapur": ["Kolhapur", "Gadhinglaj", "Jaysingpur", "Vadgaon"],
    "Solapur": ["Solapur", "Pandharpur", "Karmala", "Barshi", "Akkalkot"],
    "Ahmednagar": ["Ahmednagar", "Rahata", "Shrirampur", "Kopargaon", "Shevgaon"],
    "Amravati": ["Amravati", "Achalpur", "Daryapur", "Morshi", "Varud"],
    "Indore": ["Indore", "Sanwer", "Depalpur", "Mhow"],
    "Ujjain": ["Ujjain", "Nagda", "Khachrod", "Mahidpur"],
    "Ludhiana": ["Ludhiana", "Khanna", "Jagraon", "Samrala"],
    "Karnal": ["Karnal", "Gharaunda", "Assandh", "Taraori"],
}

# Development fallback demo records (Used strictly when official OGD API key is not configured or network fails)
DEMO_MANDI_RECORDS = [
    {
        "market": "Pune (Gultekdi APMC)",
        "district": "Pune",
        "state": "Maharashtra",
        "commodity": "Soybean",
        "variety": "Yellow",
        "grade": "FAQ",
        "min_price": 4750.0,
        "max_price": 5420.0,
        "modal_price": 5200.0,
        "unit": "₹/quintal",
        "arrival_date": "2026-09-20",
    },
    {
        "market": "Baramati APMC",
        "district": "Pune",
        "state": "Maharashtra",
        "commodity": "Soybean",
        "variety": "Yellow",
        "grade": "FAQ",
        "min_price": 4800.0,
        "max_price": 5380.0,
        "modal_price": 5150.0,
        "unit": "₹/quintal",
        "arrival_date": "2026-09-20",
    },
    {
        "market": "Khed APMC",
        "district": "Pune",
        "state": "Maharashtra",
        "commodity": "Soybean",
        "variety": "Local",
        "grade": "Medium",
        "min_price": 4600.0,
        "max_price": 5250.0,
        "modal_price": 5050.0,
        "unit": "₹/quintal",
        "arrival_date": "2026-09-20",
    },
    {
        "market": "Manchar APMC",
        "district": "Pune",
        "state": "Maharashtra",
        "commodity": "Soybean",
        "variety": "Yellow",
        "grade": "FAQ",
        "min_price": 4700.0,
        "max_price": 5300.0,
        "modal_price": 5100.0,
        "unit": "₹/quintal",
        "arrival_date": "2026-09-20",
    },
    {
        "market": "Nashik Main APMC",
        "district": "Nashik",
        "state": "Maharashtra",
        "commodity": "Onion",
        "variety": "Red",
        "grade": "FAQ",
        "min_price": 1400.0,
        "max_price": 2850.0,
        "modal_price": 2400.0,
        "unit": "₹/quintal",
        "arrival_date": "2026-09-20",
    },
    {
        "market": "Lasalgaon APMC",
        "district": "Nashik",
        "state": "Maharashtra",
        "commodity": "Onion",
        "variety": "Red / Summer",
        "grade": "Special",
        "min_price": 1600.0,
        "max_price": 3100.0,
        "modal_price": 2650.0,
        "unit": "₹/quintal",
        "arrival_date": "2026-09-20",
    },
    {
        "market": "Pimpalgaon APMC",
        "district": "Nashik",
        "state": "Maharashtra",
        "commodity": "Tomato",
        "variety": "Hybrid",
        "grade": "Medium",
        "min_price": 1200.0,
        "max_price": 2200.0,
        "modal_price": 1850.0,
        "unit": "₹/quintal",
        "arrival_date": "2026-09-20",
    },
    {
        "market": "Nagpur APMC",
        "district": "Nagpur",
        "state": "Maharashtra",
        "commodity": "Cotton",
        "variety": "Medium Staple",
        "grade": "FAQ",
        "min_price": 6800.0,
        "max_price": 7650.0,
        "modal_price": 7350.0,
        "unit": "₹/quintal",
        "arrival_date": "2026-09-20",
    },
    {
        "market": "Indore Main APMC",
        "district": "Indore",
        "state": "Madhya Pradesh",
        "commodity": "Wheat",
        "variety": "Lokwan / Sharbati",
        "grade": "FAQ",
        "min_price": 2350.0,
        "max_price": 3100.0,
        "modal_price": 2780.0,
        "unit": "₹/quintal",
        "arrival_date": "2026-09-20",
    },
]
